---
- name: Create config File - RedHat
  template:
    src='named.conf.j2'
    dest={{ named_conf_file_location }}
    owner={{ named_user }}
    group={{ named_group }}
    mode={{ named_config_mode | default("0600") }}
  when: ansible_os_family == "RedHat"
  notify: Stop named - RedHat

- name: Create included.conf File - RedHat
  template:
    src='included.conf.j2'
    dest={{ named_conf_includes_directory }}/included.conf
    owner={{ named_user }}
    group={{ named_group }}
    mode={{ named_config_mode | default("0600") }}
  when: ansible_os_family == "RedHat"
  notify: Stop named - RedHat

- name: Create zone Files - RedHat
  template:
    src='zone.j2'
    dest={{ named_conf_directory }}/masters/{{ item.key | regex_replace('_', '.') }}.zone
    owner={{ named_user }}
    group={{ named_group }}
    mode={{ named_config_mode | default("0600") }}
  with_dict: named_zones
  when: named_zones_create_masters and ansible_os_family == "RedHat"
  notify: Stop named - RedHat
