---
- name: Create config File - Debian
  template:
    src='named.conf.j2'
    dest={{ named_conf_file_location }}
    owner={{ named_user }}
    group={{ named_group }}
    mode='0600'
  when: ansible_os_family == "Debian"
  notify: Stop named - Debian

- name: Create included.conf File - Debian
  template:
    src='included.conf.j2'
    dest={{ named_conf_includes_directory }}/included.conf
    owner={{ named_user }}
    group={{ named_group }}
    mode='0600'
  when: ansible_os_family == "Debian"
  notify: Stop named - Debian

- name: Create zone Files - Debian
  template:
    src='zone.j2'
    dest={{ named_conf_directory }}/masters/{{ item.key | regex_replace('_', '.') }}.zone
    owner={{ named_user }}
    group={{ named_group }}
    mode='0600'
  with_dict: named_zones
  when: named_zones_create_masters and ansible_os_family == "Debian"
  notify: Stop named - Debian
